version: '3'
services:
  hello-world-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hello-world-demo
    container_name: hello-world-demo
    environment:
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9999 remote_autostart=1 remote_enable=1
    ports:
      - '8080:80'
    volumes:
       - './src:/var/www/html'